### PR TITLE
Issue 81: Fixed CommandGroup behavior inconsistency

### LINKED ISSUE #81: Nesting CommandGroups breaks scheduler
For our Autonomous routine, we have a custom CommandGroup that contains another custom CommandGroup that we inject at runtime.

While the Scheduler is building the CommandRunner and transversing through the commands, it assumes any inner CommandGroups it encounters must be one of the three built-in sequencing helpers and (rightfully) calls `getCommands` to grab the command list.

However, **the Scheduler breaks when you pass in a custom CommandGroup**, i.e. one which you extend yourself, because the commands are actually located under `getRoot().getCommands()`. Meanwhile, `getCommands()` returns null.

``` java
public class NestingCommandGroup extends CommandGroup {

    public NestingCommandGroup() {
        sequentially(InnerCommandGroup(), ...);
    }
}

public class InnerCommandGroup extends CommandGroup {

    public InnerCommandGroup() {
        ...
    }
}
```

The following test case should fail with a `NullPointerException`.

``` java
@Test
public void shouldExecuteInnerNamedCommand() {
    Command c = NestingCommandGroup();
    scheduler.submit(c);
    scheduler.execute(0);

    assertThat(...);
}
```

And this is the [debugger tree](https://cloud.githubusercontent.com/assets/6506631/18611447/9059cfca-7d07-11e6-864a-d05441318032.png), if it helps.

### PR DESCRIPTION
**Pull request by rothso**
Proposal to fix #81.

Subclassed CommandGroups are now indistinguishable from those created with the static helpers. This lets the Scheduler skip the `getRoot` step and forward the submitted command to the builder.

After playing around with this, I see why `root` is needed now. I decided the least invasive solution would be to remove `getRoot` (assuming it's not part of the public API) and keep the notion of root internal. Then the `getCommands` and `getType` methods would delegate to the root object if there is one.

Let me know what you think about this approach!

### CODE REVIEW

File: strongback/src/org/strongback/command/CommandGroup.java [hunk 1]
```diff
@@ -151,15 +151,19 @@ private CommandGroup(Command[] commands, Type type) {
     }
 
     Type getType() {
-        return type;
+        if (root != null) {
+            return root.type;
+        } else {
+            return type;
+        }
```
Comment (rhauch) [inline strongback/src/org/strongback/command/CommandGroup.java]: Minor nit ... since the if block returns, there is no need for an 'else' block, so it'd be better to do this:

```
if (root != null) {
    return root.type;
}
return type;
```

or, better yet:

```
return root != null ? root.type : type;
```

File: strongback/src/org/strongback/command/CommandGroup.java [hunk 2]
```diff
@@ -151,15 +151,19 @@ private CommandGroup(Command[] commands, Type type) {
...
-        return commands;
-    }
-
-    Command getRoot() {
-        return root;
+        if (root != null) {
+            return root.getCommands();
+        } else {
+            return commands;
+        }
```
Comment (rhauch) [inline strongback/src/org/strongback/command/CommandGroup.java]: Same minor nit ... since the if block returns, there is no need for an 'else' block, so it'd be better to do this:

```
if (root != null) {
    return root.getCommands();
}
return commands;
```

or, better yet:

```
return root != null ? root.getCommands() : command;
```

File: strongback/src/org/strongback/command/CommandGroup.java (hunk 1 above)
Comment (rothso) [reply strongback/src/org/strongback/command/CommandGroup.java]: Whoops, I completely forgot that was a thing. Fixed!

File: strongback/src/org/strongback/command/CommandGroup.java (hunk 2 above)
Comment (rothso) [reply strongback/src/org/strongback/command/CommandGroup.java]: Fixed again!

**Comment by rhauch** [comment]
@rothso on the surface this looks good, and I do appreciate trying to be least invasive -- this code is finicky. I see that the unit tests have passed, but have you tried running these changes with a robot?

**Comment by rhauch** [comment]
@rothso Oh, it'd also be great if you added your name in the CONTRIBUTORS.txt file.

**Comment by rothso** [comment]
Unfortunately I haven't had an opportunity to deploy to our bot yet—my next chance is this Sunday, so I'll be able to tell you how it goes then.

And alright, will do.
